version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn clean package -DskipMunitTests
      - save_cache:
          path: 
            - ~/.m2
          keys: 
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
  test: 
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn test
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn deploy -DmuleDeploy -Duri=$apuri -Dworker=$worker -Dusername=$username -Dpassword=$password -Denvironment=$environment

# Orchestrate our job run sequence
workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test 

