version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package -DskipMunitTests
  test: 
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn test
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn deploy -DmuleDeploy

# Orchestrate our job run sequence
workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test 

